command:
  - "python"
  - "-m"
  - "uvicorn"
  - "app:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: SERVING_ENDPOINT
    value: your-agent-serving-endpoint

resources:
  - name: serving-endpoint
    serving_endpoint: your-agent-serving-endpoint
    permission: CAN_QUERY
